### ISSUE TITLE
What exactly is in adata.X?

### ISSUE THREAD

**Issue by jtremblay** [eleozzr/scDML#6] opened 2024-02-27 17:17 UTC
Dear scDML developers,
I've successfully ran the tutorial2 that you provided.

I was wondering what was the nature of the matrix data in `adata.X`
For intance:
<img width="1147" alt="image" src="https://github.com/eleozzr/scDML/assets/1168411/2888dbb3-1d6e-44bf-be77-310842707d9e">

I was wondering why the values were negative?
Thanks very much,
-Julien

**Comment by yuxiaokang-source** [comment] 2024-03-03 20:39
Sorry for not replying you in time. But  I  don't understand your  question, could you discibe your problem in detail?

> Dear scDML developers, I've successfully ran the tutorial2 that you provided.
> 
> I was wondering what was the nature of the matrix data in `adata.X` For intance: <img alt="image" width="1147" src="https://private-user-images.githubusercontent.com/1168411/308273033-2888dbb3-1d6e-44bf-be77-310842707d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0OTgyNjMsIm5iZiI6MTcwOTQ5Nzk2MywicGF0aCI6Ii8xMTY4NDExLzMwODI3MzAzMy0yODg4ZGJiMy0xZDZlLTQ0YmYtYmU3Ny0zMTA4NDI3MDdkOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMjAzMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjYzBjZjY0MTBjYjJjNTAyOGU5OGYxNTM5MDAwNzBiNWI1MDVmMjdhODc1ZTYwNjc5OTljNDNlZDdlMzdkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5bQcb5AvXinrtexvD8L7mUZUBXneiIDUe4VEirIGKJ8">
> 
> I was wondering why the values were negative? Thanks very much, -Julien

**Comment by yuxiaokang-source** [comment] 2024-03-25 01:39
> Dear scDML developers, I've successfully ran the tutorial2 that you provided.
> 
> I was wondering what was the nature of the matrix data in `adata.X` For intance: <img alt="image" width="1147" src="https://private-user-images.githubusercontent.com/1168411/308273033-2888dbb3-1d6e-44bf-be77-310842707d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzA2NjEsIm5iZiI6MTcxMTMzMDM2MSwicGF0aCI6Ii8xMTY4NDExLzMwODI3MzAzMy0yODg4ZGJiMy0xZDZlLTQ0YmYtYmU3Ny0zMTA4NDI3MDdkOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMDEzMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIzNmExMTVmODQ3YzA5MTA0NTE0NjRhYTFjZjk0MzFlMGI2NTkyMTk0ZjliOWIyOThmYjEzYTE2MDM0MWE2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.InBInw66mZTS9RwP__DNeCKGucVLY-nEZ9b-YpZqLr4">
> 
> I was wondering why the values were negative? Thanks very much, -Julien

If you don't discribe the problem in detail( for example you should show me the code to reproduce the adata.X,  because I can't figure out the adata.X is the result of which step, so I can't answer your question), I will close the issue in next week.

**Closed as completed** 2024-03-28 12:18 UTC

**Comment by KatjaRun** [comment] 2025-01-22 08:44
Dear developers, 
I have also come across a similar question. The batch correction using scDML worked perfectly, but the corrected data contains negative values. I suspect these negative values result from the z-score transformation and are adjusted in the following steps, is this expected?
Additionally, I attempted to plot UMAPs of gene expression for several genes. However, the values vary across genes, making the plots look inconsistent. In your Figure 4f feature plots, the gene expression values consistently range from 0 to a maximum value. Could you clarify what was plotted there—were the values log-transformed?

Thank you, 
Katja
